// Mock data for testing without MongoDB
// Run with: node server/index.js (set NODE_ENV=test)

const mockUser = {
  _id: 'mock-user-id',
  name: 'Demo User',
  email: 'demo@cloudoptimizer.com',
  company: 'Tech Corp',
  role: 'user',
  cloudProviders: ['aws', 'azure', 'gcp'],
};

const mockCosts = {
  totalCost: 4523.45,
  costByProvider: [
    { _id: 'aws', total: 2345.67, count: 156 },
    { _id: 'azure', total: 1456.78, count: 98 },
    { _id: 'gcp', total: 721.00, count: 67 },
  ],
  costByServiceType: [
    { _id: 'compute', total: 2100.50 },
    { _id: 'storage', total: 1200.30 },
    { _id: 'database', total: 890.45 },
    { _id: 'network', total: 332.20 },
  ],
  dailyTrend: Array.from({ length: 30 }, (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - i);
    return {
      _id: date.toISOString().split('T')[0],
      total: Math.random() * 200 + 100,
    };
  }).reverse(),
  topServices: [
    { _id: 'EC2', provider: 'aws', total: 1234.56 },
    { _id: 'Virtual Machines', provider: 'azure', total: 987.65 },
    { _id: 'S3', provider: 'aws', total: 654.32 },
    { _id: 'Compute Engine', provider: 'gcp', total: 543.21 },
    { _id: 'RDS', provider: 'aws', total: 432.10 },
  ],
};

const mockRecommendations = [
  {
    _id: 'rec-1',
    user: 'mock-user-id',
    cloudProvider: 'aws',
    category: 'rightsizing',
    priority: 'high',
    title: 'Rightsize EC2 instance i-0abc123def',
    description: 'This EC2 instance has low utilization (CPU: 8%, Memory: 12%). Consider downsizing from m5.xlarge to m5.large.',
    estimatedSavings: 156.50,
    savingsPercentage: 45,
    implementationEffort: 'low',
    resourceId: 'i-0abc123def',
    resourceName: 'EC2-1',
    currentCost: 348.00,
    optimizedCost: 191.50,
    aiConfidence: 92,
    status: 'pending',
    createdAt: new Date(),
  },
  {
    _id: 'rec-2',
    user: 'mock-user-id',
    cloudProvider: 'aws',
    category: 'idle_resources',
    priority: 'high',
    title: 'Review idle EC2 instance i-0xyz789',
    description: 'This EC2 instance appears to be idle (CPU: 2%, Memory: 5%). Consider stopping or terminating if not needed.',
    estimatedSavings: 285.00,
    savingsPercentage: 100,
    implementationEffort: 'low',
    resourceId: 'i-0xyz789',
    resourceName: 'EC2-2',
    currentCost: 285.00,
    optimizedCost: 0,
    aiConfidence: 88,
    status: 'pending',
    createdAt: new Date(),
  },
  {
    _id: 'rec-3',
    user: 'mock-user-id',
    cloudProvider: 'azure',
    category: 'reserved_instances',
    priority: 'medium',
    title: 'Purchase Reserved VM Instances for Azure VMs',
    description: 'Based on consistent usage patterns for Virtual Machines, switching to Reserved Instances could save up to 30%.',
    estimatedSavings: 420.00,
    savingsPercentage: 30,
    implementationEffort: 'medium',
    currentCost: 1400.00,
    optimizedCost: 980.00,
    aiConfidence: 78,
    status: 'pending',
    createdAt: new Date(),
  },
  {
    _id: 'rec-4',
    user: 'mock-user-id',
    cloudProvider: 'gcp',
    category: 'storage_optimization',
    priority: 'low',
    title: 'Move infrequently accessed data to Nearline storage',
    description: 'Approximately 40% of your Cloud Storage data hasn\'t been accessed in 30+ days. Consider using Nearline storage.',
    estimatedSavings: 85.00,
    savingsPercentage: 25,
    implementationEffort: 'low',
    aiConfidence: 72,
    status: 'pending',
    createdAt: new Date(),
  },
  {
    _id: 'rec-5',
    user: 'mock-user-id',
    cloudProvider: 'aws',
    category: 'savings_plan',
    priority: 'medium',
    title: 'Enroll in Compute Savings Plan',
    description: 'Based on your consistent EC2 and Lambda usage, a 1-year Compute Savings Plan could save you 25%.',
    estimatedSavings: 580.00,
    savingsPercentage: 25,
    implementationEffort: 'medium',
    currentCost: 2320.00,
    optimizedCost: 1740.00,
    aiConfidence: 82,
    status: 'in_progress',
    createdAt: new Date(),
  },
];

const mockResources = [
  {
    _id: 'res-1',
    user: 'mock-user-id',
    cloudProvider: 'aws',
    resourceType: 'EC2',
    resourceId: 'i-0abc123',
    resourceName: 'EC2-1',
    region: 'us-east-1',
    status: 'underutilized',
    utilization: { cpu: 8, memory: 12, storage: 45, network: 20 },
    cost: 156.50,
    currency: 'USD',
    specifications: { vcpu: '4', memory: '16 GB', storage: '100 GB' },
    lastScannedAt: new Date(),
  },
  {
    _id: 'res-2',
    user: 'mock-user-id',
    cloudProvider: 'aws',
    resourceType: 'EC2',
    resourceId: 'i-0xyz789',
    resourceName: 'EC2-2',
    region: 'us-west-2',
    status: 'idle',
    utilization: { cpu: 2, memory: 5, storage: 10, network: 5 },
    cost: 285.00,
    currency: 'USD',
    specifications: { vcpu: '8', memory: '32 GB', storage: '200 GB' },
    lastScannedAt: new Date(),
  },
  {
    _id: 'res-3',
    user: 'mock-user-id',
    cloudProvider: 'azure',
    resourceType: 'VM',
    resourceId: 'vm-azure-001',
    resourceName: 'Azure-VM-1',
    region: 'eastus',
    status: 'optimal',
    utilization: { cpu: 65, memory: 72, storage: 55, network: 40 },
    cost: 320.00,
    currency: 'USD',
    specifications: { vcpu: '4', memory: '16 GB', storage: '128 GB' },
    lastScannedAt: new Date(),
  },
  {
    _id: 'res-4',
    user: 'mock-user-id',
    cloudProvider: 'gcp',
    resourceType: 'Compute Instance',
    resourceId: 'gcp-inst-001',
    resourceName: 'GCP-Instance-1',
    region: 'us-central1',
    status: 'running',
    utilization: { cpu: 45, memory: 58, storage: 70, network: 35 },
    cost: 210.00,
    currency: 'USD',
    specifications: { vcpu: '2', memory: '8 GB', storage: '50 GB' },
    lastScannedAt: new Date(),
  },
];

const mockBudgets = [
  {
    _id: 'budget-1',
    user: 'mock-user-id',
    name: 'Monthly AWS Budget',
    cloudProvider: 'aws',
    amount: 5000,
    currency: 'USD',
    period: 'monthly',
    startDate: new Date(new Date().setDate(1)),
    actualSpend: 2345.67,
    percentageUsed: '46.91',
    status: 'active',
    alertsEnabled: true,
  },
  {
    _id: 'budget-2',
    user: 'mock-user-id',
    name: 'Monthly Azure Budget',
    cloudProvider: 'azure',
    amount: 3000,
    currency: 'USD',
    period: 'monthly',
    startDate: new Date(new Date().setDate(1)),
    actualSpend: 1456.78,
    percentageUsed: '48.56',
    status: 'active',
    alertsEnabled: true,
  },
  {
    _id: 'budget-3',
    user: 'mock-user-id',
    name: 'Total Cloud Budget',
    cloudProvider: 'all',
    amount: 10000,
    currency: 'USD',
    period: 'monthly',
    startDate: new Date(new Date().setDate(1)),
    actualSpend: 4523.45,
    percentageUsed: '45.23',
    status: 'active',
    alertsEnabled: true,
  },
];

module.exports = {
  mockUser,
  mockCosts,
  mockRecommendations,
  mockResources,
  mockBudgets,
};
